# Generated by Django 3.0.5 on 2020-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='projects/images/%Y/%m/%d')),
                ('url', models.URLField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
