# Generated by Django 3.0.5 on 2020-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WoodObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wood_obj/%y/%m/%d')),
                ('type', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
