# Generated by Django 3.0.5 on 2020-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200511_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comment',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
    ]
